"""empty message

Revision ID: e483fec00ef1
Revises: 631eb2a7cabb
Create Date: 2022-11-23 23:34:19.612998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e483fec00ef1'
down_revision = '631eb2a7cabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('species', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.Column('created', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('name', table_name='charater')
    op.drop_index('name_2', table_name='charater')
    op.drop_table('charater')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charater',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('species', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'charater', ['name'], unique=False)
    op.create_index('name', 'charater', ['name'], unique=False)
    op.drop_table('favorites')
    op.drop_table('character')
    # ### end Alembic commands ###
